/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19_simulationn;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author abdurrahman_sefer
 */
public class HistogramPanel extends javax.swing.JPanel {

    Graphics g;
    Histogram_verileri histogram_verileri;

    /**
     * Creates new form HistogramPanel
     */
    public HistogramPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        this.g = g;
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        try {
            cizmeye_devam(g);
        } catch (InterruptedException ex) {
            Logger.getLogger(HistogramPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        super.paintComponents(g);
    }

    void cizmeye_devam(Graphics g) throws InterruptedException {

        if (histogram_verileri != null) {
            int oran = 1;
            if (histogram_verileri.getToplam_kislerin_sayisi() >= 10000) {
                oran = 150;
            } else if (histogram_verileri.getToplam_kislerin_sayisi() >= 1000) {
                oran = 15;
            }

            g.setColor(Color.green);
            g.drawString(histogram_verileri.getEnfekte_olmamis_kisiler() + "", 100, (this.getHeight() - histogram_verileri.getEnfekte_olmamis_kisiler() - 10) / oran);
            g.drawRect(50, this.getHeight() - histogram_verileri.getEnfekte_olmamis_kisiler(), 100, (histogram_verileri.getEnfekte_olmamis_kisiler()) / oran);
            g.fillRect(50, this.getHeight() - histogram_verileri.getEnfekte_olmamis_kisiler(), 100, (histogram_verileri.getEnfekte_olmamis_kisiler()) / oran);

            g.setColor(Color.RED);
            g.drawString(histogram_verileri.getPozitif_kisiler() + "", 220 + 50, (this.getHeight() - histogram_verileri.getPozitif_kisiler() - 10) / oran);
            g.drawRect(220, this.getHeight() - histogram_verileri.getPozitif_kisiler(), 100, histogram_verileri.getPozitif_kisiler() / oran);

            g.fillRect(220, this.getHeight() - histogram_verileri.getPozitif_kisiler(), 100, histogram_verileri.getPozitif_kisiler() / oran);

            g.setColor(Color.BLUE);
            g.drawString(histogram_verileri.getIyilesen_kisiler() + "", 400 + 50, (this.getHeight() - histogram_verileri.getIyilesen_kisiler() - 10) / oran);
            g.drawRect(400, this.getHeight() - histogram_verileri.getIyilesen_kisiler(), 100, histogram_verileri.getIyilesen_kisiler() / oran);

            g.fillRect(400, this.getHeight() - histogram_verileri.getIyilesen_kisiler(), 100, histogram_verileri.getIyilesen_kisiler() / oran);

            this.repaint();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void draw_histogram(Histogram_verileri histogram_verileri) {
        this.histogram_verileri = histogram_verileri;
        this.repaint();
//        if (histogram_verileri.getToplam_kislerin_sayisi() < 100) {

//
//        } else {
//
//        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
