/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19_simulationn;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author abdurrahman_sefer
 */
public class simulation_pan extends javax.swing.JPanel {

    /**
     * Creates new form simulation_pan
     */
    public simulation_pan() {
        initComponents();
    }

    panel panel_ayarlari;
    Graphics g;
    ArrayList<person> liste;
    
  

    @Override
    public void paint(Graphics g) {
        this.g = g;
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        try {
            drawe_person_metod(g);
        } catch (InterruptedException ex) {
            Logger.getLogger(simulation_pan.class.getName()).log(Level.SEVERE, null, ex);
        }
        super.paintComponents(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    int x = 0;
    int y = 0;

    void drawe_person(ArrayList<person> liste, panel panel_ayarlari) {
       // this.removeAll();
        this.liste = liste;
        this.panel_ayarlari = panel_ayarlari; 
        this.repaint();
    }

    private void drawe_person_metod(Graphics g) throws InterruptedException {
        
               
        if (liste != null) {
            for (int i = 0; i < liste.size(); i++) {
                x = liste.get(i).getPx();
                y = liste.get(i).getPy();                             
                if (liste.get(i).getHasta_durumu() == 0){
                    g.setColor(Color.green);
                } else if (liste.get(i).getHasta_durumu() == 1) {
                    if (liste.get(i).getSon_duruma_gecen_zaman() >= panel_ayarlari.getIyilesme_suersi()) {
                        g.setColor(Color.blue);
                    } else {
                        g.setColor(Color.red);
                    }
                } else {
                    g.setColor(Color.blue);
                }
                g.fillOval(x, y, 10, 10);               
            }
            this.repaint();          
        }

    }

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
